version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: java -jar ./task-app-master-degree-all.jar
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/task-app
      - DB_USERNAME=postgres
      - DB_PASSWORD=Tolstochok3000
      - DB_SCHEMA=public

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "task-app"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Tolstochok3000"
    ports:
      - "5432:5432"
    restart: always